#!/bin/bash

if test ! "$(which gcc)"; then
  echo "Installing xcode..."
  xcode-select --install
fi

if test ! "$(which brew)"; then
  echo "Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  brew update
fi

if test ! "$(which ansible)"; then
  echo "Installing ansible..."
  brew install ansible
else
  brew upgrade ansible
fi

if test ! "$(which ansible)"; then
  echo "Not supported yet."
  exit 1
fi

ansible-playbook playbook.yml

# Add bootstrap either here or to handle anything we can't do
# with playbook or dotfiles
