- name: Install OSX-only core packages
  package: name={{ item }}
  when: is_osx
  with_items:
    - coreutils
    - findutils
    - gawk
    - gnu-getopt
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnutls
    - gpg
    - grc
    - pstree
    - unrar
    - watch

- name: Install core packages
  package: name={{ item }}
  with_items:
    - curl
    - git
    - htop
    - vim
    - wget
    - zsh
    - ncdu
    - tree

- name: Gets the zsh path
  shell: which zsh
  register: bin_zsh
  changed_when: False

- name: Add homebrew zsh to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: "{{ bin_zsh.stdout }}"
  become: True

- name: Install OSX-only apps
  homebrew_cask: name={{ item }}
  when: is_osx
  with_items:
    - appcleaner
    - day-o
    - slate
    # https://github.com/sindresorhus/quick-look-plugins
    - betterzipql
    #- qlcolorcode
    - qlimagesize
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - quicklook-csv
    - quicklook-json
    - suspicious-package
    - webpquicklook

    