---
# Update homebrew and cask

- name: Update homebrew
  homebrew:
    state: latest
    update_homebrew: yes

- name: Tap Homebrew casks
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions
    - neovim/homebrew-neovim
